import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Inter } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";
import { createClient } from "@/lib/supabase/server";


config.autoAddCss = false; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>){
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  let perfilUrl = '/Login'
  if (user) {
    const { data: usuario } = await supabase
      .from('usuarios')
      .select('rol, id_estudiante, id_encargado')
      .eq('auth_id', user.id)
      .single()

    if (usuario?.rol === 'estudiante')
      perfilUrl = `/Perfil/estudiante/${usuario.id_estudiante}`
  }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body 
      className="min-h-full flex flex-col">
        <Header isLoggedIn={!!user} perfilUrl={perfilUrl} />
        {children}
        <Footer/>
      </body>
    </html>
    
  );
}
